# Pandas tutorial

In [79]:
from operator import index

import pandas as pd
from jedi.api import strings
from matplotlib import dates

In [80]:
#check pandas version
print(pd.__version__)

3.0.6

# Series create, manipulate, querry, delete

In [81]:
# creating a series from a list
arr = [0, 1, 2, 3, 4]
s1 = pd.Series(arr)
s1

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [82]:
order = [1, 2, 3, 4, 5]
s2 = pd.Series(arr, index=order)
s2

1    0
2    1
3    2
4    3
5    4
dtype: int64

In [83]:
import numpy as np
n=np.random.randn(5) #Create a random Ndarray
n

array([-0.73034563,  2.39688257,  0.85579196,  0.15030275, -0.98030662])

In [84]:
import numpy as np

n = np.random.randn(5)  #Create a random Ndarray
index = ['a', 'b', 'c', 'd', 'e']
s2 = pd.Series(n, index=index)
s2

a   -2.026762
b   -0.730410
c   -0.145462
d    1.155765
e   -0.066101
dtype: float64

In [85]:
#create series from dictionary
d={'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
s3 = pd.Series(d)
s3

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [86]:
#you can mopdify the index of series
print(s1)
s1.index = ['A', 'B', 'C', 'D', 'E']
s1

0    0
1    1
2    2
3    3
4    4
dtype: int64

A    0
B    1
C    2
D    3
E    4
dtype: int64

In [87]:
#slicing
s1[:3]

A    0
B    1
C    2
dtype: int64

In [88]:
s4 = s1._append_internal(s3)
s4

A    0
B    1
C    2
D    3
E    4
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [89]:
s4.drop('e')

A    0
B    1
C    2
D    3
E    4
a    1
b    2
c    3
d    4
dtype: int64

In [90]:
s4

A    0
B    1
C    2
D    3
E    4
a    1
b    2
c    3
d    4
e    5
dtype: int64

# Series Operations

In [91]:
arr1=[0, 1, 2, 3, 4, 5, 7]
arr2=[6, 7, 8, 9, 5]

In [92]:
s5=pd.Series(arr2)
s5

0    6
1    7
2    8
3    9
4    5
dtype: int64

In [93]:
s6 = pd.Series(arr2)

In [94]:
s5=pd.Series(arr2)
s5

0    6
1    7
2    8
3    9
4    5
dtype: int64

In [95]:
s6 = pd.Series(arr1)
s6

0    0
1    1
2    2
3    3
4    4
5    5
6    7
dtype: int64

In [96]:
s5.add(s6)

0     6.0
1     8.0
2    10.0
3    12.0
4     9.0
5     NaN
6     NaN
dtype: float64

In [97]:
s5.sub(s6)

0    6.0
1    6.0
2    6.0
3    6.0
4    1.0
5    NaN
6    NaN
dtype: float64

In [98]:
s5.mul(s6)

0     0.0
1     7.0
2    16.0
3    27.0
4    20.0
5     NaN
6     NaN
dtype: float64

In [99]:
s5.div

<bound method Series.truediv of 0    6
1    7
2    8
3    9
4    5
dtype: int64>

In [100]:
s5.div(s6)

0     inf
1    7.00
2    4.00
3    3.00
4    1.25
5     NaN
6     NaN
dtype: float64

In [101]:
s6.median()

np.float64(3.0)

In [102]:
print('median', s6.median())
print('max', s6.median())
print('min', s6.min())

median 3.0
max 3.0
min 0

# Create Dataframe

In [103]:
dates=pd.date_range('today', periods=6) #Define time sequence as index
num_arr=np.random.randn(6, 4) #Import numpy random array
colums=['A', 'B', 'C', 'D'] #Use the table as the column name

df1 = pd.DataFrame(num_arr, index=dates, columns=colums)
df1

                                   A         B         C         D
2026-09-23 02:54:03.966915 -0.145899 -1.713809  0.308601  0.833971
2026-09-24 02:54:03.966915 -0.566623  1.842636 -2.085969  0.512029
2026-09-25 02:54:03.966915 -0.291451  0.466791  1.034546  1.758664
2026-09-26 02:54:03.966915  0.280670  0.505811  0.461894  1.095940
2026-09-27 02:54:03.966915  2.383115  0.105783  0.176775 -0.387047
2026-09-28 02:54:03.966915  1.389259  1.576528 -0.221850  0.221893

In [104]:
#create dataframe with dictionary array

data = {'animal': ['cat', 'cat', 'snake','dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'], 'age':[2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7,3], 'visits':[1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no'] }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df2 = pd.DataFrame(data, index=labels)
df2

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [105]:
#see datatypes of array
df2.dtypes

animal          str
age         float64
visits        int64
priority        str
dtype: object

In [106]:
df2.head()

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no

In [107]:
df2.tail(3)

  animal  age  visits priority
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [108]:
print(df2.index)
df2.columns

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='str')

Index(['animal', 'age', 'visits', 'priority'], dtype='str')

In [109]:
df2.values

array([['cat', 2.5, 1, 'yes'],
       ['cat', 3.0, 3, 'yes'],
       ['snake', 0.5, 2, 'no'],
       ['dog', nan, 3, 'yes'],
       ['dog', 5.0, 2, 'no'],
       ['cat', 2.0, 3, 'no'],
       ['snake', 4.5, 1, 'no'],
       ['cat', nan, 1, 'yes'],
       ['dog', 7.0, 2, 'no'],
       ['dog', 3.0, 1, 'no']], dtype=object)

In [110]:
df2.describe( )  #see statitical data of datarame

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [111]:
df2.T

            a    b      c    d    e    f      g    h    i    j
animal    cat  cat  snake  dog  dog  cat  snake  cat  dog  dog
age       2.5  3.0    0.5  NaN  5.0  2.0    4.5  NaN  7.0  3.0
visits      1    3      2    3    2    3      1    1    2    1
priority  yes  yes     no  yes   no   no     no  yes   no   no

In [112]:
df2.sort_values(by='age')

  animal  age  visits priority
c  snake  0.5       2       no
f    cat  2.0       3       no
a    cat  2.5       1      yes
b    cat  3.0       3      yes
j    dog  3.0       1       no
g  snake  4.5       1       no
e    dog  5.0       2       no
i    dog  7.0       2       no
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [113]:
#slicing dataframe
df2[1:3]

  animal  age  visits priority
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [114]:
#query dataframe by tag
df2[['age', 'visits']]

   age  visits
a  2.5       1
b  3.0       3
c  0.5       2
d  NaN       3
e  5.0       2
f  2.0       3
g  4.5       1
h  NaN       1
i  7.0       2
j  3.0       1

In [115]:
df2.iloc[1:3] # Query rows 2,3

  animal  age  visits priority
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [116]:
df3 =df2.copy()
df3

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [117]:
df3.isnull()

   animal    age  visits  priority
a   False  False   False     False
b   False  False   False     False
c   False  False   False     False
d   False   True   False     False
e   False  False   False     False
f   False  False   False     False
g   False  False   False     False
h   False   True   False     False
i   False  False   False     False
j   False  False   False     False

In [123]:
df3.loc['f', 'age']=1.5
df3

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [126]:
df3.mean(numeric_only=True)

age       3.375
visits    1.900
dtype: float64

In [127]:
df3.sum

<bound method DataFrame.sum of   animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no>

In [128]:
strings = pd.Series(['A', 'B', 'C', 'D', 'Aaa', 'BaCa', np.nan, 'CBA', ' cow', 'owl'])
strings.str.lower()

0       a
1       b
2       c
3       d
4     aaa
5    baca
6     NaN
7     cba
8     cow
9     owl
dtype: str

# Operations for DataFrame missing values

In [129]:
df4 = df3.copy()
df4

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [130]:
df5 = df3.copy()
df5.dropna(how='any')

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
i    dog  7.0       2       no
j    dog  3.0       1       no

# DataFrame file operations

In [131]:
df3.to_csv('animal.csv')

In [132]:
df_animal=pd.read_csv('animal.csv')
df_animal.head(3)

  Unnamed: 0 animal  age  visits priority
0          a    cat  2.5       1      yes
1          b    cat  3.0       3      yes
2          c  snake  0.5       2       no

In [134]:
df3.to_excel

<bound method NDFrame.to_excel of   animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no>

In [136]:
df3.to_excel('animal.xlsx', sheet_name='Sheet1')
df_animal2 = pd.read_excel('animal.xlsx', 'Sheet1', index_col=None, na_values=['NA'])
df_animal2

  Unnamed: 0 animal  age  visits priority
0          a    cat  2.5       1      yes
1          b    cat  3.0       3      yes
2          c  snake  0.5       2       no
3          d    dog  NaN       3      yes
4          e    dog  5.0       2       no
5          f    cat  1.5       3       no
6          g  snake  4.5       1       no
7          h    cat  NaN       1      yes
8          i    dog  7.0       2       no
9          j    dog  3.0       1       no